version: "3"

services:
  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
  mongo-user:
    container_name: mongo-user
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - shared_database:/data/db1
  mongo-product:
    container_name: mongo-product
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - shared_database:/data/db

  user:
    container_name: user-app
    restart: always
    build: ../User
    ports:
      - "5000:5000"
    links:
      - mongo-user
      - rabbitmq
  product:
    container_name: product-app
    restart: always
    build: ../Product
    ports:
      - "8000:6000"
    links:
      - mongo-product
      - rabbitmq
volumes:
  shared_database:
